meta_product_name: "Blank."
meta_title: "Blank. - Bring ideas to creative people"
meta_description: "Blank. is a plateform for creative people looking for new project ideas"
meta_image: "cover.png" # should exist in `app/assets/images/`
